jenkins:
  systemMessage: "Ceph Jenkins Controller"
  numExecutors: 0
  mode: EXCLUSIVE

  # Security configuration
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"

  # Authorization configuration
  authorizationStrategy:
    globalMatrix:
      entries:
        - user:
            name: "admin"
            permissions:
              - "Overall/Administer"
        - user:
            name: "anonymous"
            permissions:
              - "Overall/Read"

  # Cloud agent configuration
  clouds:
    - docker:
        name: "podman-cloud"
        containerCap: 10
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/podman.sock"
        templates:
          - name: "ceph-seed-agent"
            labelString: "ceph-seed-agent"
            remoteFs: "/home/jenkins"
            mode: EXCLUSIVE
            pullStrategy: PULL_NEVER
            dockerTemplateBase:
              image: "ceph-jenkins-seed-agent:latest"
              user: "jenkins"
            connector:
              attach: {}
          - name: "ceph-build-agent"
            labelString: "ceph-build-agent"
            remoteFs: "/home/jenkins"
            mode: EXCLUSIVE
            pullStrategy: PULL_NEVER
            dockerTemplateBase:
              image: "ceph-jenkins-build-agent:latest"
              user: "jenkins"
            connector:
              attach: {}

security:
  globalJobDslSecurityConfiguration:
    # Allow Job DSL to run without manual script approval.
    useScriptSecurity: false
  scriptApproval:
    # Allow the specific DSL scripts to bypass the sandbox.
    approvedSignatures:
      - "method javaposse.jobdsl.dsl.DslFactory job java.lang.String"
      - "method javaposse.jobdsl.dsl.Job scm(groovy.lang.Closure)"


# Seeder job
jobs:
  - file: "/var/jenkins_home/seed.groovy"
