jenkins:
  systemMessage: "Ceph Jenkins Controller"
  numExecutors: 1
  mode: EXCLUSIVE
  labelString: "controller"

  # Security configuration
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"

  # Authorization configuration
  authorizationStrategy:
    globalMatrix:
      entries:
        - user:
            name: "admin"
            permissions:
              - "Overall/Administer"
        - user:
            name: "anonymous"
            permissions:
              - "Overall/Read"

  # Agent node configuration
  nodes:
    - permanent:
        name: "ceph-agent"
        remoteFS: "/home/jenkins"
        labelString: "teuthology"
        mode: NORMAL
        numExecutors: 10
        launcher:
          ssh:
            port: 22
            credentialsId: "ceph-agent-ssh-key"
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"

  # Cloud agent configuration
  clouds:
    - docker:
        name: "podman-cloud"
        containerCap: 5
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/podman.sock"
        templates:
          - name: "ceph-agent"
            labelString: "ceph-podman-agent"
            remoteFs: "/home/jenkins"
            mode: EXCLUSIVE
            dockerTemplateBase:
              image: "ceph-jenkins-agent:latest"
              pullStrategy: PULL_NEVER
              user: "jenkins"
            connector:
              attach: {}

# Credentials configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: "ceph-agent-ssh-key"
              username: "jenkins"
              description: "SSH Key for agent nodes"

security:
  globalJobDslSecurityConfiguration:
    # Allow Job DSL to run without manual script approval.
    useScriptSecurity: false
  scriptApproval:
    # Allow the specific DSL scripts to bypass the sandbox.
    approvedSignatures:
      - "method javaposse.jobdsl.dsl.DslFactory job java.lang.String"
      - "method javaposse.jobdsl.dsl.Job scm(groovy.lang.Closure)"


# Seeder job
jobs:
  - file: "/var/jenkins_home/seed.groovy"
