pipeline {
    agent {
        label "ceph-build-centos-stream9-agent"
    }

    environment {
        // Environment & Variable Setup
        DISTRO="centos"
        RELEASE="9"
        DIST="el9"
        BRANCH="${params.CEPH_BRANCH}"
        FLAVOR="default"

        // Set up a build configs and paths for build artifacts
        BASE_VERSION="19.0.0"
        RPM_BUILDAREA="${WORKSPACE}/rpm/${DIST}"
        RELEASE_BUILDAREA="${WORKSPACE}/release/${DIST}"
        CEPH_DIR="${WORKSPACE}/ceph"
    }

    stages {
        stage("Checkout") {
            steps {
                echo "Checking out Ceph source code ..."

                // Pull Ceph source code
                dir("${CEPH_DIR}") {
                    script {
                        echo "Updating existing repository and submodules ..."
                        checkout([
                            $class: "GitSCM",
                            branches: [[name: "${params.CEPH_BRANCH}"]],
                            extensions: [
                                [$class: "CleanBeforeCheckout", deleteUntrackedNestedRepositories: true],
                                [$class: "CloneOption", depth: 1, shallow: true],
                                [$class: "SubmoduleOption",
                                    disableSubmodules: false,
                                    parentCredentials: true,
                                    recursiveSubmodules: true,
                                    shallow: true
                                ]
                            ],
                            userRemoteConfigs: [[url: "${params.CEPH_REPO}"]]
                        ])

                        // Verify commit and get sha and short sha from git
                        sh 'git log -1 --oneline'
                        env.SHA1 = sh(
                            script: 'git rev-parse HEAD 2>/dev/null || echo "unknown"',
                            returnStdout: true
                        ).trim()
                        env.SHORT_SHA = sh(
                            script: 'git rev-parse --short HEAD 2>/dev/null || echo "unknown"',
                            returnStdout: true
                        ).trim()
                    }
                }
            }
        }

        stage("Build RPMs") {
            steps {
                echo "Running the Ceph RPM build script ..."

                // Run bash script you mentioned earlier
                dir("${CEPH_DIR}") {
                    script {
                        sh "chmod +x ${WORKSPACE}/containers/agents/build/centos-stream9/build_rpm"
                        sh "source ${WORKSPACE}/containers/agents/build/centos-stream9/build_rpm"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "RPMs built successfully! Archiving ..."

            // Save the RPMs
            archiveArtifacts artifacts: "${RPM_BUILDAREA}/RPMS/*.rpm", fingerprint: true
        }

        failure {
            echo "Build failed. Check the logs for GCC or CMake errors."
        }
    }
}