def publish_to_pulp(artifactPath, distro, distroVersion, arch) {
    withCredentials([usernamePassword(
        credentialsId: "pulp-credentials",
        usernameVariable: "PULP_USER",
        passwordVariable: "PULP_PASS"
    )]) {
        sh """
            ${PULP_PROJECT_DIR}/scripts/configure-client.sh \
                --username "\$PULP_USER" \
                --password "\$PULP_PASS" \
                --overwrite
        """
    }
    sh """
        set -e
        ${PULP_PUBLISH_SCRIPT} '${artifactPath}' \
            --branch '${params.CEPH_BRANCH}' \
            --sha1 '${env.SHA1}' \
            --distro '${distro}' \
            --distro-version '${distroVersion}' \
            --arch '${arch}' \
            --flavor '${params.FLAVOR}'
    """
    echo "Published: ${env.PULP_SERVER_URL}/pulp/content/repos/ceph/${params.CEPH_BRANCH}/${env.SHA1}/${distro}/${distroVersion}/flavors/${params.FLAVOR}/"
}

pipeline {
    agent none

    options {
        // Keep the last 20 builds
        buildDiscarder(logRotator(numToKeepStr: "20"))

        // Do not checkout code automatically
        skipDefaultCheckout()

        // Timestamps in console output
        timestamps()

        // Colorize console output
        ansiColor("xterm")
    }

    environment {
        // Set shared workspace path
        SHARED_WS="/home/jenkins/workspace/${JOB_NAME}/${BUILD_NUMBER}"

        // Environment & Variable Setup
        REPO_URL="https://shaman.ceph.com/r/ceph"

        // Set user build parameters
        RPM_BUILD_OPTS="${params.RPM_BUILD_OPTS}"

        // Set up a build paths for artifacts
        CEPH_DIR="${SHARED_WS}/ceph"
        ARTIFACTS_DIR="${SHARED_WS}/artifacts"

        // Set up build scripts
        BUILD_BINARY="${SHARED_WS}/jobs/pipelines/sample_ceph_build_ci/build_binary.sh"
        BUILD_RPM = "${SHARED_WS}/containers/agents/build/centos/build_rpm"
        BUILD_RPM_ROCKY10 = "${SHARED_WS}/containers/agents/build/centos/build_rpm"
        BUILD_DEB = "${SHARED_WS}/containers/agents/build/ubuntu/build_deb"

        PULP_PROJECT_DIR="${SHARED_WS}/pulp-project"
        PULP_PUBLISH_SCRIPT="${SHARED_WS}/pulp-project/scripts/publish-packages.sh"
    }

    stages {
        stage("Checkout and Build Binary") {
            agent {
                node {
                    label "ceph-build-fedora39-agent"
                }
            }

            stages {
                stage("Checkout Repositories") {
                    steps {
                        // Clone the Jenkinsfile repository
                        dir("${SHARED_WS}") {
                            checkout scm
                        }

                        // Clone the Pulp project repository
                        dir("${PULP_PROJECT_DIR}") {
                            checkout([
                                $class: "GitSCM",
                                branches: [[name: "main"]],
                                extensions: [
                                    [$class: "CloneOption", depth: 1,
                                        shallow: true, noTags: true]
                                ],
                                userRemoteConfigs: [
                                    [url: "${env.PULP_PROJECT_REPO}"]
                                ]
                            ])
                        }
                        sh "chmod +x ${PULP_PROJECT_DIR}/scripts/*.sh"
                    }
                }

                stage("Checkout Ceph Repository") {
                    steps {
                        echo "Checking out Ceph source code ..."

                        // Pull Ceph source code
                        dir("${CEPH_DIR}") {
                            script {
                                echo "Updating existing repository and submodules ..."

                                // clone + submodules complete before next step
                                checkout([
                                    $class: "GitSCM",
                                    branches: [[name: "${params.CEPH_BRANCH}"]],
                                    extensions: [
                                        [$class: "CleanBeforeCheckout",
                                            deleteUntrackedNestedRepositories: true],
                                        [$class: "CloneOption", depth: 1, shallow: true,
                                            noTags: false],
                                        [$class: "SubmoduleOption",
                                            disableSubmodules: false,
                                            parentCredentials: true,
                                            recursiveSubmodules: true,
                                            shallow: true
                                        ]
                                    ],
                                    userRemoteConfigs: [[url: "${params.CEPH_REPO}"]]
                                ])

                                // Ensure submodules are fully checked out before proceeding
                                sh(
                                    script: "git submodule status --recursive",
                                    label: "Verify submodules"
                                )

                                // fetch all tags
                                sh(
                                    script: "git fetch --tags --unshallow || git fetch --tags",
                                    label: "Fetch all tags"
                                )
                            }
                        }
                    }
                }

                stage("Build Binary") {
                    steps {
                        echo "Running the Ceph binary build script ..."

                        dir("${CEPH_DIR}") {
                            script {
                                // Generate the SHA1 and VERSION
                                env.SHA1 = sh(
                                    script: "git rev-parse HEAD 2>/dev/null || echo \"unknown\"",
                                    returnStdout: true
                                ).trim()
                                env.VERSION = sh(
                                    script: "git describe --abbrev=8 --match \"v*\" --always " +
                                        "| sed \"s/^v//\"",
                                    returnStdout: true
                                ).trim()

                                // Replace last '-' with '.' in VERSION
                                env.VERSION = sh(
                                    script: "echo $VERSION | sed \"s/-/./2\"", returnStdout: true
                                ).trim()

                                // Run build_binary script
                                sh "chmod +x ${BUILD_BINARY} && ${BUILD_BINARY}"
                            }
                        }
                    }
                }
            }
        }

        stage("Build Artifacts") {
            parallel {
                stage("CentOS 9.Stream") {
                    when {
                        allOf {
                            expression {
                                return params.DISTRO.tokenize().contains("centos9")
                            }
                            expression {
                                return params.ARCH.tokenize().contains("x86_64")
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-centos9-agent"
                        }
                    }
                    environment {
                        RPM_BUILDAREA="${SHARED_WS}/rpm/centos9"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/centos9"
                        DIST="centos"
                        DIST_VERSION="9"
                    }
                    steps {
                        echo "Running the Ceph RPM build script ..."

                        // Run build_rpm script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_RPM} && ${BUILD_RPM}"
                            }
                        }

                        // Archive RPMs
                        echo "RPMs for CentOS 9 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/centos9") {
                            sh "mkdir -p x86_64 noarch SRPMS"
                            sh """
                                rsync -a \\
                                    ${RPM_BUILDAREA}/RPMS/x86_64 \\
                                    ${RPM_BUILDAREA}/RPMS/noarch \\
                                    ${RPM_BUILDAREA}/SRPMS \\
                                    .
                            """
                        }

                        script {
                            if (params.PUBLISH_ARTIFACTS) {
                                for (arch in ["x86_64", "noarch", "SRPMS"]) {
                                    def artifactPath = "${ARTIFACTS_DIR}/centos9/${arch}"
                                    if (fileExists(artifactPath)) {
                                        publish_to_pulp(artifactPath, "${DIST}", "${DIST_VERSION}", arch)
                                    }
                                }
                            }
                        }
                    }
                }

                stage("Rocky Linux 10") {
                    when {
                        allOf {
                            expression {
                                return params.DISTRO.tokenize().contains("rocky10")
                            }
                            expression {
                                return params.ARCH.tokenize().contains("x86_64")
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-rocky10-agent"
                        }
                    }
                    environment {
                        RPM_BUILDAREA="${SHARED_WS}/rpm/rocky10"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/rocky10"
                        DIST="rocky"
                        DIST_VERSION="10"
                    }
                    steps {
                        echo "Running the Ceph RPM build script ..."

                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_RPM_ROCKY10} && ${BUILD_RPM_ROCKY10}"
                            }
                        }

                        echo "RPMs for Rocky 10 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/rocky10") {
                            sh """
                                rsync -a \\
                                    ${RPM_BUILDAREA}/RPMS/x86_64 \\
                                    ${RPM_BUILDAREA}/RPMS/noarch \\
                                    ${RPM_BUILDAREA}/SRPMS \\
                                    .
                            """
                        }

                        script {
                            if (params.PUBLISH_ARTIFACTS) {
                                for (arch in ["x86_64", "noarch", "SRPMS"]) {
                                    def artifactPath = "${ARTIFACTS_DIR}/rocky10/${arch}"
                                    if (fileExists(artifactPath)) {
                                        publish_to_pulp(artifactPath, "${DIST}", "${DIST_VERSION}", arch)
                                    }
                                }
                            }
                        }
                    }
                }

                stage("Ubuntu 22.04 (jammy)") {
                    when {
                        allOf {
                            expression {
                                return params.DISTRO.tokenize().contains("jammy")
                            }
                            expression {
                                return params.ARCH.tokenize().contains("x86_64")
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-ubuntu-jammy-agent"
                        }
                    }
                    environment {
                        DIST="ubuntu"
                        DIST_VERSION="jammy"
                        DEB_BUILDAREA="${SHARED_WS}/deb/${DIST_VERSION}"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/${DIST_VERSION}"
                        ARCH="x86_64"
                    }
                    steps {
                        echo "Running the Ceph DEB build script ..."

                        // Run build_deb script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_DEB} && ${BUILD_DEB}"
                            }
                        }

                        // Archive DEBs
                        echo "DEBs for Ubuntu 22.04 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/${DIST_VERSION}/${ARCH}") {
                            sh """
                                rsync -a \\
                                    ${RELEASE_BUILDAREA}/db \\
                                    ${RELEASE_BUILDAREA}/dists \\
                                    ${RELEASE_BUILDAREA}/pool \\
                                    .
                            """
                        }

                        script {
                            if (params.PUBLISH_ARTIFACTS) {
                                def artifactPath = "${ARTIFACTS_DIR}/${DIST_VERSION}/${ARCH}/pool"
                                if (fileExists(artifactPath)) {
                                    publish_to_pulp(artifactPath, "${DIST}", "${DIST_VERSION}", "${ARCH}")
                                }
                            }
                        }
                    }
                }

                stage("Ubuntu 24.04 (noble)") {
                    when {
                        allOf {
                            expression {
                                return params.DISTRO.tokenize().contains("noble")
                            }
                            expression {
                                return params.ARCH.tokenize().contains("x86_64")
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-ubuntu-noble-agent"
                        }
                    }
                    environment {
                        DIST="ubuntu"
                        DIST_VERSION="noble"
                        DEB_BUILDAREA="${SHARED_WS}/deb/${DIST_VERSION}"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/${DIST_VERSION}"
                        ARCH="x86_64"
                    }
                    steps {
                        echo "Running the Ceph DEB build script ..."

                        // Run build_deb script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_DEB} && ${BUILD_DEB}"
                            }
                        }

                        // Archive DEBs
                        echo "DEBs for Ubuntu 24.04 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/${DIST_VERSION}/${ARCH}") {
                            sh """
                                rsync -a \\
                                    ${RELEASE_BUILDAREA}/db \\
                                    ${RELEASE_BUILDAREA}/dists \\
                                    ${RELEASE_BUILDAREA}/pool \\
                                    .
                            """
                        }

                        script {
                            if (params.PUBLISH_ARTIFACTS) {
                                def artifactPath = "${ARTIFACTS_DIR}/${DIST_VERSION}/${ARCH}/pool"
                                if (fileExists(artifactPath)) {
                                    publish_to_pulp(artifactPath, "${DIST}", "${DIST_VERSION}", "${ARCH}")
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            node("ceph-build-fedora39-agent") {
                ws("${SHARED_WS}") {
                    script {
                        // Archive whatever artifacts were produced
                        if (fileExists("artifacts")) {
                            echo "Archiving RPMs and DEBs ..."
                            archiveArtifacts(
                                artifacts: "artifacts/**", allowEmptyArchive: true
                            )
                        }

                        sh "LC_ALL=C find '${SHARED_WS}' -depth -name '*[^[:print:]]*' -exec rm -rf {} + || true"

                        echo "Cleaning up shared workspace ..."
                        cleanWs(disableDeferredWipeout: true, deleteDirs: true)
                    }
                }
            }
        }
    }
}