pipeline {
    agent none

    options {
        // Keep the last 20 builds
        buildDiscarder(logRotator(numToKeepStr: "20"))

        // Do not checkout code automatically
        skipDefaultCheckout()

        // Timestamps in console output
        timestamps()

        // Colorize console output
        ansiColor("xterm")
    }

    environment {
        // Set shared workspace path
        SHARED_WS="/home/jenkins/workspace/${JOB_NAME}/${BUILD_NUMBER}"

        // Environment & Variable Setup
        REPO_URL="https://shaman.ceph.com/r/ceph"

        // Set user build parameters
        RPM_BUILD_OPTS="${params.RPM_BUILD_OPTS}"

        // Set up a build paths for artifacts
        CEPH_DIR="${SHARED_WS}/ceph"
        ARTIFACTS_DIR="${SHARED_WS}/artifacts"

        // Set up build scripts
        BUILD_BINARY="${SHARED_WS}/jobs/pipelines/sample_ceph_build_ci/build_binary.sh"
        BUILD_RPM = "${SHARED_WS}/containers/agents/build/centos/build_rpm"
        BUILD_RPM_ROCKY10 = "${SHARED_WS}/containers/agents/build/centos/build_rpm"
        BUILD_DEB = "${SHARED_WS}/containers/agents/build/ubuntu/build_deb"
    }

    stages {
        stage("Checkout and Build Binary") {
            agent {
                node {
                    label "ceph-build-fedora39-agent"
                }
            }

            stages {
                stage("Checkout Pipeline Code") {
                    steps {
                        // Pull the Jenkinsfile repository
                        dir("${SHARED_WS}") {
                            checkout scm
                        }
                    }
                }

                stage("Checkout Ceph Repository") {
                    steps {
                        echo "Checking out Ceph source code ..."

                        // Pull Ceph source code
                        dir("${CEPH_DIR}") {
                            script {
                                echo "Updating existing repository and submodules ..."

                                // clone + submodules complete before next step
                                checkout([
                                    $class: "GitSCM",
                                    branches: [[name: "${params.CEPH_BRANCH}"]],
                                    extensions: [
                                        [$class: "CleanBeforeCheckout",
                                            deleteUntrackedNestedRepositories: true],
                                        [$class: "CloneOption", depth: 1, shallow: true,
                                            noTags: false],
                                        [$class: "SubmoduleOption",
                                            disableSubmodules: false,
                                            parentCredentials: true,
                                            recursiveSubmodules: true,
                                            shallow: true
                                        ]
                                    ],
                                    userRemoteConfigs: [[url: "${params.CEPH_REPO}"]]
                                ])

                                // Ensure submodules are fully checked out before proceeding
                                sh(
                                    script: "git submodule status --recursive",
                                    label: "Verify submodules"
                                )

                                // fetch all tags
                                sh(
                                    script: "git fetch --tags --unshallow || git fetch --tags",
                                    label: "Fetch all tags"
                                )
                            }
                        }
                    }
                }

                stage("Build Binary") {
                    steps {
                        echo "Running the Ceph binary build script ..."

                        dir("${CEPH_DIR}") {
                            script {
                                // Generate the SHA1 and VERSION
                                env.SHA1 = sh(
                                    script: "git rev-parse HEAD 2>/dev/null || echo \"unknown\"",
                                    returnStdout: true
                                ).trim()
                                env.VERSION = sh(
                                    script: "git describe --abbrev=8 --match \"v*\" --always " +
                                        "| sed \"s/^v//\"",
                                    returnStdout: true
                                ).trim()

                                // Replace last '-' with '.' in VERSION
                                env.VERSION = sh(
                                    script: "echo $VERSION | sed \"s/-/./2\"", returnStdout: true
                                ).trim()

                                // Run build_binary script
                                sh "chmod +x ${BUILD_BINARY} && ${BUILD_BINARY}"
                            }
                        }
                    }
                }
            }
        }

        stage("Build RPMs and DEBs") {
            parallel {
                stage("Build CentOS 9 RPMs") {
                    when {
                        expression {
                            allOf {
                                expression {
                                    return "centos9" in params.DISTRO
                                }
                                expression {
                                    return "x86_64" in params.ARCH
                                }
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-centos9-agent"
                        }
                    }
                    environment {
                        RPM_BUILDAREA="${SHARED_WS}/rpm/centos9"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/centos9"
                    }
                    steps {
                        echo "Running the Ceph RPM build script ..."

                        // Run build_rpm script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_RPM} && ${BUILD_RPM}"
                            }
                        }

                        // Archive RPMs
                        echo "RPMs for CentOS 9 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/centos9") {
                            sh "mkdir -p x86_64 noarch SRPMS"
                            sh """
                                rsync -a \\
                                    ${RPM_BUILDAREA}/RPMS/x86_64 \\
                                    ${RPM_BUILDAREA}/RPMS/noarch \\
                                    ${RPM_BUILDAREA}/SRPMS \\
                                    .
                            """
                        }
                    }
                }

                stage("Build Rocky 10 RPMs") {
                    when {
                        expression {
                            allOf {
                                expression {
                                    return "rocky10" in params.DISTRO
                                }
                                expression {
                                    return "x86_64" in params.ARCH
                                }
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-rocky10-agent"
                        }
                    }
                    environment {
                        RPM_BUILDAREA="${SHARED_WS}/rpm/rocky10"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/rocky10"
                    }
                    steps {
                        echo "Running the Ceph RPM build script ..."

                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_RPM_ROCKY10} && ${BUILD_RPM_ROCKY10}"
                            }
                        }

                        echo "RPMs for Rocky 10 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/rocky10") {
                            sh """
                                rsync -a \\
                                    ${RPM_BUILDAREA}/RPMS/x86_64 \\
                                    ${RPM_BUILDAREA}/RPMS/noarch \\
                                    ${RPM_BUILDAREA}/SRPMS \\
                                    .
                            """
                        }
                    }
                }

                stage("Build Ubuntu 22.04 DEBs") {
                    when {
                        expression {
                            allOf {
                                expression {
                                    return "jammy" in params.DISTRO
                                }
                                expression {
                                    return "x86_64" in params.ARCH
                                }
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-ubuntu-jammy-agent"
                        }
                    }
                    environment {
                        DEB_BUILDAREA="${SHARED_WS}/deb/jammy"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/jammy"
                        DIST="jammy"
                    }
                    steps {
                        echo "Running the Ceph DEB build script ..."

                        // Run build_deb script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_DEB} && ${BUILD_DEB}"
                            }
                        }

                        // Archive DEBs
                        echo "DEBs for Ubuntu 22.04 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/jammy") {
                            sh """
                                rsync -a \\
                                    ${RELEASE_BUILDAREA}/db \\
                                    ${RELEASE_BUILDAREA}/dists \\
                                    ${RELEASE_BUILDAREA}/pool \\
                                    .
                            """
                        }
                    }
                }

                stage("Build Ubuntu 24.04 DEBs") {
                    when {
                        expression {
                            allOf {
                                expression {
                                    return "noble" in params.DISTRO
                                }
                                expression {
                                    return "x86_64" in params.ARCH
                                }
                            }
                        }
                    }
                    agent {
                        node {
                            label "ceph-build-ubuntu-noble-agent"
                        }
                    }
                    environment {
                        DEB_BUILDAREA="${SHARED_WS}/deb/noble"
                        RELEASE_BUILDAREA="${SHARED_WS}/release/noble"
                        DIST="noble"
                    }
                    steps {
                        echo "Running the Ceph DEB build script ..."

                        // Run build_deb script
                        dir("${CEPH_DIR}") {
                            script {
                                sh "chmod +x ${BUILD_DEB} && ${BUILD_DEB}"
                            }
                        }

                        // Archive DEBs
                        echo "DEBs for Ubuntu 24.04 built successfully! Archiving ..."
                        dir("${ARTIFACTS_DIR}/noble") {
                            sh """
                                rsync -a \\
                                    ${RELEASE_BUILDAREA}/db \\
                                    ${RELEASE_BUILDAREA}/dists \\
                                    ${RELEASE_BUILDAREA}/pool \\
                                    .
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            node("ceph-build-fedora39-agent") {
                ws("${SHARED_WS}") {
                    script {
                        // Archive whatever artifacts were produced
                        if (fileExists("artifacts")) {
                            echo "Archiving RPMs and DEBs ..."
                            archiveArtifacts(
                                artifacts: "artifacts/**", allowEmptyArchive: true
                            )
                        }

                        // Clean up the shared workspace
                        echo "Cleaning up shared workspace ..."
                        cleanWs(disableDeferredWipeout: true, deleteDirs: true)
                    }
                }
            }
        }
    }
}