# Official base jenkins LTS image
FROM jenkins/jenkins:lts

# Build Arguments
ARG AGENT_UID=1000
ARG AGENT_GID=1001
ARG AGENT_USER=jenkins
ARG AGENT_GROUP=jenkins-bridge

# Synchronize UID/GID with the Podman host
USER root
RUN groupadd -g ${AGENT_GID} ${AGENT_GROUP} || true && \
    usermod -aG ${AGENT_GID} jenkins

# Jenkins configurations
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV CASC_JENKINS_CONFIG="/var/jenkins_home/casc_configs"

# Copy the plugin list
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins using the plugin manager CLI
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Create the config directory
RUN mkdir -p /var/jenkins_home/casc_configs && \
    chown -R jenkins:jenkins /var/jenkins_home/casc_configs

# Set user to jenkins
USER jenkins
